// web/src/app/components/command-palette/command-palette.component.ts
import { Component, HostListener, Output, EventEmitter, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SERVICES_DATA, ServiceItem } from '../../data/services.data';
import { HARDWARE_NODES, HardwareNode } from '../../data/hardware.data';
import { TOPOLOGY_NODES, TopologyNode } from '../../data/topology.data';
import { TranslationService } from '../../services/translation.service';

interface SearchResultItem {
  id: string;
  title: string;
  category: string;
  subtext: string;
  type: 'service' | 'hardware' | 'vlan' | 'command' | 'doc';
  actionData?: any;
}

@Component({
  selector: 'app-command-palette',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (isOpen) {
      <div class="fixed inset-0 z-[100] flex items-start justify-center pt-16 sm:pt-24 px-4 bg-black/80 backdrop-blur-md animate-fadeIn" (click)="close()">
        
        <div class="w-full max-w-2xl bg-obsidian-900 border border-obsidian-700 rounded-2xl shadow-2xl overflow-hidden font-sans flex flex-col max-h-[80vh]" (click)="$event.stopPropagation()">
          
          <!-- Search Header -->
          <div class="p-4 border-b border-obsidian-750 flex items-center gap-3 bg-obsidian-950">
            <span class="text-slate-300 font-mono text-base">⌘</span>
            <input
              #searchInput
              type="text"
              [value]="query"
              (input)="onInput($event)"
              [placeholder]="ts.isRomanian ? 'Caută servicii, noduri, porturi, comenzi CLI (ex: ollama, zfs, vlan, npm)...' : 'Search services, nodes, ports, CLI commands (e.g. ollama, zfs, vlan, npm)...'"
              class="w-full bg-transparent text-slate-100 placeholder:text-slate-500 font-sans text-sm outline-none"
            />
            <button (click)="close()" class="text-xs font-mono text-slate-400 hover:text-slate-200 px-2 py-1 rounded bg-obsidian-800 border border-obsidian-700">ESC</button>
          </div>

          <!-- Quick Filters -->
          <div class="flex items-center gap-1.5 px-4 py-2 bg-obsidian-950/60 border-b border-obsidian-750 text-xs font-mono overflow-x-auto no-scrollbar">
            <button (click)="activeFilter = 'all'" [class.text-slate-300]="activeFilter === 'all'" [class.bg-slate-400/10]="activeFilter === 'all'" class="px-2.5 py-1 rounded-md text-slate-400 hover:text-slate-200 transition-colors">{{ ts.isRomanian ? "Toate" : "All" }}</button>
            <button (click)="activeFilter = 'service'" [class.text-slate-300]="activeFilter === 'service'" [class.bg-slate-400/10]="activeFilter === 'service'" class="px-2.5 py-1 rounded-md text-slate-400 hover:text-slate-200 transition-colors">{{ ts.isRomanian ? "Servicii" : "Services" }} ({{ services.length }})</button>
            <button (click)="activeFilter = 'hardware'" [class.text-slate-300]="activeFilter === 'hardware'" [class.bg-slate-400/10]="activeFilter === 'hardware'" class="px-2.5 py-1 rounded-md text-slate-400 hover:text-slate-200 transition-colors">Hardware ({{ hardware.length }})</button>
            <button (click)="activeFilter = 'command'" [class.text-slate-300]="activeFilter === 'command'" [class.bg-slate-400/10]="activeFilter === 'command'" class="px-2.5 py-1 rounded-md text-slate-400 hover:text-slate-200 transition-colors">{{ ts.isRomanian ? "Comenzi CLI" : "CLI Commands" }}</button>
          </div>

          <!-- Results List -->
          <div class="flex-1 overflow-y-auto p-3 space-y-1 text-xs font-sans max-h-[55vh]">
            @if (filteredResults.length === 0) {
              <div class="p-8 text-center text-slate-400 font-sans text-xs">
                {{ ts.isRomanian ? 'Niciun rezultat găsit pentru: ' : 'No results found for: ' }} <span class="text-slate-300 font-mono">"{{ query }}"</span>
              </div>
            }

            @for (item of filteredResults; track item.id) {
              <div
                (click)="onSelect(item)"
                class="flex items-center justify-between p-3 rounded-xl hover:bg-obsidian-800/80 border border-transparent hover:border-obsidian-700 transition-all cursor-pointer group"
              >
                <div class="flex items-center gap-3">
                  <div class="w-7 h-7 rounded-lg bg-obsidian-950 border border-obsidian-750 flex items-center justify-center font-mono font-bold text-[10px] text-slate-300">
                    {{ item.type === 'service' ? 'SRV' : item.type === 'hardware' ? 'HW' : item.type === 'command' ? 'CLI' : 'DOC' }}
                  </div>
                  <div>
                    <div class="font-bold text-slate-100 group-hover:text-slate-300 transition-colors text-xs flex items-center gap-2">
                      <span>{{ item.title }}</span>
                      <span class="text-[10px] font-mono text-slate-400 font-normal px-1.5 py-0.2 rounded bg-obsidian-950 border border-obsidian-750">{{ item.category }}</span>
                    </div>
                    <div class="text-[11px] text-slate-400 font-mono mt-0.5 truncate max-w-md">
                      {{ item.subtext }}
                    </div>
                  </div>
                </div>

                <div class="text-right font-mono text-[11px] text-slate-500 group-hover:text-slate-300 flex items-center gap-1">
                  <span>{{ ts.isRomanian ? 'Accesează' : 'Jump' }}</span>
                  <span>→</span>
                </div>
              </div>
            }
          </div>

          <!-- Palette Footer -->
          <div class="p-3 bg-obsidian-950 border-t border-obsidian-750 text-[11px] font-mono text-slate-400 flex items-center justify-between">
            <div class="flex items-center gap-3">
              <span><kbd class="px-1.5 py-0.5 rounded bg-obsidian-850 border border-obsidian-700 text-slate-300">↑↓</kbd> {{ ts.isRomanian ? "Navighează" : "Navigate" }}</span>
              <span><kbd class="px-1.5 py-0.5 rounded bg-obsidian-850 border border-obsidian-700 text-slate-300">↵</kbd> {{ ts.isRomanian ? "Selectează" : "Select" }}</span>
            </div>
            <span class="text-slate-300">{{ ts.isRomanian ? "Datacenter // Căutare Rapidă (⌘K)" : "Datacenter // Quick Search (⌘K)" }}</span>
          </div>

        </div>

      </div>
    }
  `
})
export class CommandPaletteComponent {
  @Output() nodeFocused = new EventEmitter<TopologyNode>();

  ts = inject(TranslationService);
  isOpen = false;
  query = '';
  activeFilter: 'all' | 'service' | 'hardware' | 'command' = 'all';

  services: ServiceItem[] = SERVICES_DATA;
  hardware: HardwareNode[] = HARDWARE_NODES;

  cliCommands = [
    { id: 'cmd-ollama', title: 'Ollama Inference Test', category: 'CLI / AI', subtext: 'curl -s http://192.168.1.110:11434/api/tags', type: 'command' as const },
    { id: 'cmd-zfs', title: 'ZFS Pool Status Check', category: 'CLI / Storage', subtext: 'zpool status -v && zfs list -o space', type: 'command' as const },
    { id: 'cmd-pct', title: 'Proxmox Container List', category: 'CLI / Proxmox', subtext: 'pct list && qm list', type: 'command' as const },
    { id: 'cmd-dr', title: 'Disaster Recovery vzdump Runner', category: 'CLI / DR', subtext: './scripts/disaster-recovery/dr_vzdump_restore.sh proxmox', type: 'command' as const },
    { id: 'cmd-chaos', title: 'Chaos 100% CPU Stress Runner', category: 'CLI / Chaos', subtext: './scripts/chaos/chaos_runner.sh cpu-stress 60', type: 'command' as const },
    { id: 'cmd-trivy', title: 'Trivy IaC & Container Security Scan', category: 'CLI / DevSecOps', subtext: 'trivy config ./terraform && trivy fs .', type: 'command' as const },
    { id: 'cmd-fw-verify', title: 'Enterprise Dual-Tier Firewall & Forensics Verification', category: 'CLI / Cyber', subtext: './scripts/verify-enterprise-firewall.sh', type: 'command' as const }
  ];

  @HostListener('window:keydown', ['$event'])
  handleKeyDown(event: KeyboardEvent) {
    if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
      event.preventDefault();
      this.toggle();
    } else if (event.key === 'Escape' && this.isOpen) {
      this.close();
    }
  }

  toggle() {
    this.isOpen = !this.isOpen;
    if (this.isOpen) {
      this.query = '';
    }
  }

  open() {
    this.isOpen = true;
    this.query = '';
  }

  close() {
    this.isOpen = false;
  }

  onInput(e: Event) {
    this.query = (e.target as HTMLInputElement).value;
  }

  get filteredResults(): SearchResultItem[] {
    const q = this.query.toLowerCase().trim();
    let results: SearchResultItem[] = [];

    // Add Services
    if (this.activeFilter === 'all' || this.activeFilter === 'service') {
      for (const s of this.services) {
        results.push({
          id: 'srv-' + s.id,
          title: s.name,
          category: `Service · ${s.category.toUpperCase()}`,
          subtext: `${s.node} · ${s.domain} · Port :${s.port || 'N/A'} · RAM: ${s.ram}`,
          type: 'service',
          actionData: s
        });
      }
    }

    // Add Hardware
    if (this.activeFilter === 'all' || this.activeFilter === 'hardware') {
      for (const h of this.hardware) {
        results.push({
          id: 'hw-' + h.id,
          title: h.name,
          category: `Hardware · ${h.machine}`,
          subtext: `${h.cpu} · ${h.ram} · ${h.storage} · IP: ${h.ip}`,
          type: 'hardware',
          actionData: h
        });
      }
    }

    // Add CLI Commands
    if (this.activeFilter === 'all' || this.activeFilter === 'command') {
      for (const c of this.cliCommands) {
        results.push({
          id: c.id,
          title: c.title,
          category: c.category,
          subtext: c.subtext,
          type: 'command',
          actionData: c
        });
      }
    }

    if (!q) return results.slice(0, 12);

    return results.filter(r =>
      r.title.toLowerCase().includes(q) ||
      r.category.toLowerCase().includes(q) ||
      r.subtext.toLowerCase().includes(q)
    );
  }

  onSelect(item: SearchResultItem) {
    this.close();

    if (item.type === 'service') {
      const srv = item.actionData as ServiceItem;
      const found = TOPOLOGY_NODES.find(n => n.id === srv.id || n.name.toLowerCase().includes(srv.name.toLowerCase()));
      if (found) {
        this.nodeFocused.emit(found);
      }
      const el = document.getElementById('services');
      if (el) el.scrollIntoView({ behavior: 'smooth' });
    } else if (item.type === 'hardware') {
      const hw = item.actionData as HardwareNode;
      const found = TOPOLOGY_NODES.find(n => n.id === hw.id);
      if (found) {
        this.nodeFocused.emit(found);
      }
      const el = document.getElementById('hardware');
      if (el) el.scrollIntoView({ behavior: 'smooth' });
    } else if (item.type === 'command') {
      navigator.clipboard.writeText(item.subtext);
      const el = document.getElementById('blueprint');
      if (el) el.scrollIntoView({ behavior: 'smooth' });
    }
  }
}

// web/src/components/ui/CommandPalette.tsx
"use client";

import React, { useState, useEffect, useRef, useMemo } from "react";
import { topologyNodes, TopologyNode, SubsystemCategory } from "@/data/infrastructure";
import { services, ServiceItem } from "@/data/services";
import { Search, Terminal, ArrowRight, X, Sparkles, Server, Shield, Globe, Zap } from "lucide-react";

interface CommandPaletteProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectNode: (node: TopologyNode) => void;
  onSelectSubsystem: (subsystem: SubsystemCategory) => void;
  onResetView: () => void;
}

interface CommandAction {
  id: string;
  type: "command" | "node" | "subsystem";
  title: string;
  subtitle: string;
  category?: string;
  icon?: any;
  action: () => void;
}

export const CommandPalette: React.FC<CommandPaletteProps> = ({
  isOpen,
  onClose,
  onSelectNode,
  onSelectSubsystem,
  onResetView,
}) => {
  const [query, setQuery] = useState("");
  const [selectedIndex, setSelectedIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 50);
      setSelectedIndex(0);
      setQuery("");
    }
  }, [isOpen]);

  // Build command actions list
  const allActions: CommandAction[] = useMemo(() => {
    const list: CommandAction[] = [];

    // System Navigation Commands
    list.push(
      {
        id: "cmd-reset",
        type: "command",
        title: "reset view",
        subtitle: "Reset 3D camera to global cluster overview",
        icon: Globe,
        action: () => {
          onResetView();
          onClose();
        },
      },
      {
        id: "cmd-compute",
        type: "subsystem",
        title: "go compute",
        subtitle: "Inspect dual hypervisors and KVM virtualization tier",
        icon: Server,
        action: () => {
          onSelectSubsystem("compute");
          onClose();
        },
      },
      {
        id: "cmd-security",
        type: "subsystem",
        title: "go security",
        subtitle: "Focus on OPNsense, Wazuh XDR SIEM, and Suricata IPS",
        icon: Shield,
        action: () => {
          onSelectSubsystem("security");
          onClose();
        },
      },
      {
        id: "cmd-elo",
        type: "subsystem",
        title: "go elo",
        subtitle: "Focus on ELO Autonomous AI control plane and LLM cascade",
        icon: Zap,
        action: () => {
          onSelectSubsystem("elo");
          onClose();
        },
      },
      {
        id: "cmd-edge",
        type: "subsystem",
        title: "go edge",
        subtitle: "Focus on ESP32 microcontrollers and physical IoT sensors",
        icon: Sparkles,
        action: () => {
          onSelectSubsystem("edge");
          onClose();
        },
      }
    );

    // Add all 44 Topology Nodes
    topologyNodes.forEach((node) => {
      list.push({
        id: `node-${node.id}`,
        type: "node",
        title: node.hostname ? `${node.hostname} // ${node.name}` : node.name,
        subtitle: `${node.sublabel || node.domain || node.ip || ""} · Tier ${node.tier} (${node.category})`,
        category: node.category,
        action: () => {
          onSelectNode(node);
          onClose();
        },
      });
    });

    return list;
  }, [onClose, onResetView, onSelectNode, onSelectSubsystem]);

  // Filter actions based on query
  const filteredActions = useMemo(() => {
    if (!query.trim()) return allActions.slice(0, 10);
    const q = query.toLowerCase().trim();
    return allActions
      .filter(
        (item) =>
          item.title.toLowerCase().includes(q) ||
          item.subtitle.toLowerCase().includes(q) ||
          (item.category && item.category.toLowerCase().includes(q))
      )
      .slice(0, 12);
  }, [allActions, query]);

  // Keyboard navigation inside palette
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!isOpen) return;

      if (e.key === "Escape") {
        e.preventDefault();
        onClose();
      } else if (e.key === "ArrowDown") {
        e.preventDefault();
        setSelectedIndex((prev) => (prev + 1) % filteredActions.length);
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        setSelectedIndex((prev) =>
          prev === 0 ? filteredActions.length - 1 : prev - 1
        );
      } else if (e.key === "Enter" && filteredActions[selectedIndex]) {
        e.preventDefault();
        filteredActions[selectedIndex].action();
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, filteredActions, selectedIndex, onClose]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center pt-20 px-4 bg-espresso-950/60 backdrop-blur-md font-sans"
      onClick={onClose}
    >
      <div
        className="w-full max-w-xl bg-warm-card border border-warm rounded-2xl shadow-2xl overflow-hidden text-warm-primary animate-in fade-in zoom-in-95 duration-150"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Search Input Bar */}
        <div className="p-4 border-b border-warm flex items-center gap-3 bg-warm-page/50">
          <Terminal className="w-5 h-5 text-terracotta-500" />
          <input
            ref={inputRef}
            type="text"
            value={query}
            onChange={(e) => {
              setQuery(e.target.value);
              setSelectedIndex(0);
            }}
            placeholder="Search nodes, hostnames, IPs, or type 'go security'..."
            className="w-full bg-transparent border-none outline-none font-mono text-sm text-warm-primary placeholder:text-warm-secondary"
          />
          {query && (
            <button
              onClick={() => setQuery("")}
              className="text-warm-secondary hover:text-warm-primary"
            >
              <X className="w-4 h-4" />
            </button>
          )}
          <kbd className="px-1.5 py-0.5 rounded bg-warm-page text-[10px] font-mono border border-warm text-warm-secondary">
            ESC
          </kbd>
        </div>

        {/* Results List */}
        <div className="max-h-[380px] overflow-y-auto p-2 space-y-1">
          {filteredActions.length === 0 ? (
            <div className="p-8 text-center text-xs font-mono text-warm-secondary">
              No matching infrastructure nodes or commands found for "{query}".
            </div>
          ) : (
            filteredActions.map((item, idx) => {
              const isSelected = idx === selectedIndex;
              return (
                <button
                  key={item.id}
                  onClick={item.action}
                  onMouseEnter={() => setSelectedIndex(idx)}
                  className={`w-full flex items-center justify-between p-3 rounded-xl text-left transition-all ${
                    isSelected
                      ? "bg-terracotta-500/15 border border-terracotta-500/40 text-warm-primary"
                      : "border border-transparent hover:bg-warm-page text-warm-secondary"
                  }`}
                >
                  <div className="flex items-center gap-3">
                    <div
                      className={`p-2 rounded-lg ${
                        isSelected
                          ? "bg-terracotta-500 text-sand-50"
                          : "bg-warm-page text-warm-secondary"
                      }`}
                    >
                      {item.icon ? (
                        <item.icon className="w-4 h-4" />
                      ) : (
                        <Search className="w-4 h-4" />
                      )}
                    </div>
                    <div>
                      <div className="text-xs font-mono font-bold text-warm-primary">
                        {item.title}
                      </div>
                      <div className="text-[11px] text-warm-secondary">
                        {item.subtitle}
                      </div>
                    </div>
                  </div>
                  <ArrowRight
                    className={`w-4 h-4 transition-transform ${
                      isSelected
                        ? "text-terracotta-500 translate-x-0.5"
                        : "text-warm-secondary/40"
                    }`}
                  />
                </button>
              );
            })
          )}
        </div>

        {/* Footer Navigation Hints */}
        <div className="p-3 border-t border-warm bg-warm-page/60 flex items-center justify-between text-[10px] font-mono text-warm-secondary">
          <div className="flex items-center gap-3">
            <span>
              <kbd className="px-1 py-0.5 rounded bg-warm-card border border-warm">↑↓</kbd> Navigate
            </span>
            <span>
              <kbd className="px-1 py-0.5 rounded bg-warm-card border border-warm">↵</kbd> Select
            </span>
          </div>
          <span>HOMELAB DIGITAL TWIN // CLI</span>
        </div>
      </div>
    </div>
  );
};
